"""New Migration

Revision ID: 91b6d84eec0b
Revises: e27c73c2f126
Create Date: 2025-03-02 19:24:48.901797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91b6d84eec0b'
down_revision: Union[str, None] = 'e27c73c2f126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shipments', 'restored_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'restored_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shipments', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
