"""New Migration

Revision ID: a239fd11d6c0
Revises: ab4b7ca12a64
Create Date: 2025-03-02 15:40:18.327820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a239fd11d6c0'
down_revision: Union[str, None] = 'ab4b7ca12a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('is_deleted', sa.BOOLEAN(), nullable=False))
    op.add_column('shipments', sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'deleted_at')
    op.drop_column('shipments', 'is_deleted')
    # ### end Alembic commands ###
