"""New Migration

Revision ID: ab4b7ca12a64
Revises: 
Create Date: 2025-03-02 15:37:06.147856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4b7ca12a64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('time', sa.INTEGER(), nullable=False),
    sa.Column('weight_kg', sa.FLOAT(), nullable=False),
    sa.Column('volume_m3', sa.FLOAT(), nullable=False),
    sa.Column('eta_min', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), nullable=False),
    sa.Column('forecast_origin_wind_velocity_mph', sa.FLOAT(), nullable=False),
    sa.Column('forecast_origin_wind_direction', sa.VARCHAR(length=255), nullable=False),
    sa.Column('forecast_origin_precipitation_chance', sa.FLOAT(), nullable=False),
    sa.Column('forecast_origin_precipitation_kind', sa.VARCHAR(length=255), nullable=False),
    sa.Column('origin_solar_system', sa.VARCHAR(length=255), nullable=False),
    sa.Column('origin_planet', sa.VARCHAR(length=255), nullable=False),
    sa.Column('origin_country', sa.VARCHAR(length=255), nullable=False),
    sa.Column('origin_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('destination_solar_system', sa.VARCHAR(length=255), nullable=False),
    sa.Column('destination_planet', sa.VARCHAR(length=255), nullable=False),
    sa.Column('destination_country', sa.VARCHAR(length=255), nullable=False),
    sa.Column('destination_address', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    # ### end Alembic commands ###
