"""New Migration

Revision ID: e27c73c2f126
Revises: e3fe6b1ec9af
Create Date: 2025-03-02 19:21:23.917073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e27c73c2f126'
down_revision: Union[str, None] = 'e3fe6b1ec9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'created_at')
    # ### end Alembic commands ###
