"""New Migration

Revision ID: e3fe6b1ec9af
Revises: a239fd11d6c0
Create Date: 2025-03-02 19:20:02.791197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3fe6b1ec9af'
down_revision: Union[str, None] = 'a239fd11d6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('is_restored', sa.BOOLEAN(), nullable=False))
    op.add_column('shipments', sa.Column('restored_at', postgresql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'restored_at')
    op.drop_column('shipments', 'is_restored')
    # ### end Alembic commands ###
